"""Add per_cow_report_id to cow_reports

Revision ID: af5ce6b82142
Revises: b87c54c70922
Create Date: 2025-06-16 01:41:05.709547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af5ce6b82142'
down_revision: Union[str, None] = 'b87c54c70922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cow_reports', sa.Column('per_cow_report_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('unique_cow_report', 'cow_reports', ['cow_id', 'per_cow_report_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_cow_report', 'cow_reports', type_='unique')
    op.drop_column('cow_reports', 'per_cow_report_id')
    # ### end Alembic commands ###
