"""Add CowReport table

Revision ID: b87c54c70922
Revises: 
Create Date: 2025-06-16 01:20:54.996219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87c54c70922'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cow_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=True),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cow_reports_id'), 'cow_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cow_reports_id'), table_name='cow_reports')
    op.drop_table('cow_reports')
    # ### end Alembic commands ###
